<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW3SeltG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW3SeltG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW3SeltG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW3SeltG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW3SeltG\App_KernelDevDebugContainer([
    'container.build_hash' => 'W3SeltG',
    'container.build_id' => '485a2d42',
    'container.build_time' => 1632170977,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW3SeltG');
