<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7HLveXn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7HLveXn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7HLveXn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7HLveXn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7HLveXn\App_KernelDevDebugContainer([
    'container.build_hash' => '7HLveXn',
    'container.build_id' => '645c4c9a',
    'container.build_time' => 1630956829,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7HLveXn');
